[build]
  # Directory to change to before starting a build
  base = "."
  
  # Build command
  command = "npm run build"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist/public"

# Redirect all requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (optional)
[build.environment]
  NODE_VERSION = "20"
